production:
  clients:
    default:
      uri: <%= ENV.fetch('CONNECTION_URL'){''}%>
      options:
        auth_mech: :scram
        auth_source: admin
  options:

development:
  clients:
    default:
      uri: <%= ENV.fetch('CONNECTION_URL'){''}%>
      options:
        auth_mech: :scram
        auth_source: admin
  options:

test:
  clients:
    default:
      uri: <%= ENV.fetch('CONNECTION_URL'){''}%>_test
      options:
        auth_mech: :scram
        auth_source: admin
