production:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI'){''}%>
      options:
        auth_mech: :scram
        auth_source: admin
  options:

development:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI'){''}%>
      options:
        auth_mech: :scram
        auth_source: admin
  options:

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI'){''}%>_test
      options:
        auth_mech: :scram
        auth_source: admin
